# Generated by Django 4.0.4 on 2022-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_remove_projectdetail_project_image_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='text_service_index',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='index',
            name='text_service_index_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
